# Generated by Django 4.1.7 on 2023-03-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eachcategorypages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
