# Generated by Django 4.1.7 on 2023-02-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='carousel_photos')),
                ('carousel_text', models.CharField(max_length=200)),
            ],
        ),
    ]
