# Generated by Django 4.1.7 on 2023-02-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carousel_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_home',
            name='carousel_img',
            field=models.ImageField(upload_to='home_photos'),
        ),
    ]
